project_name: ahb_slave_mem_testbench
output_dir: ./output
dut:
  module_name: ahb_slave_mem
  source_files:
  - UVM/AHB/ahb_slave_mem.v
  parameters:
    ADDR_WIDTH: 32
    DATA_WIDTH: 32
  dut_parameters: {}
interfaces:
- name: vif_0
  protocol: ahb
  type: slave
  port_map:
    HCLK: hclk
    HRESETn: hresetn
    HADDR: haddr
    HTRANS: htrans
    HWRITE: hwrite
    HSIZE: hsize
    HWDATA: hwdata
    HRDATA: hrdata
    HREADY: hready
    HRESP: hresp
    HSELx: hsel
test_plan:
  constraints:
    addr:
      min: 0
      max: 1023
      align: 4
    data:
      type: random
    iterations: 100
  coverage:
    addr_ranges:
    - name: low
      range:
      - 0
      - 255
    - name: mid
      range:
      - 256
      - 511
    - name: high
      range:
      - 512
      - 767
    - name: very_high
      range:
      - 768
      - 1023
    corner_cases:
    - 'boundary_addr: 0x0'
    - 'boundary_addr: 0xFF'
    - 'boundary_addr: 0x400'
    - 'boundary_addr: 0x7FF'
