project_name: APB_REG_tb
output_dir: ./output
dut:
  module_name: APB_REG
  source_files:
  - UVM/APB/APB_REG.v
  parameters:
    REG_NUM_BITS: 4
  dut_parameters: {}
interfaces:
- name: vif_0
  protocol: apb
  type: master
  port_map:
    CLK: pclk
    RESETn: presetn
    i_psel: psel
    i_penable: penable
    i_pwrite: pwrite
    i_paddr: paddr
    i_pwdata: pwdata
    o_prdata: prdata
    o_pready: pready
    o_pslverr: pslverr
test_plan:
  constraints:
    addr:
      min: 0
      max: 60            # REG_NUM_BITS=4: 16 words x 4 bytes = 64 bytes (0x00-0x3C)
      align: 4
    data:
      type: random
    iterations: 100      # Reduced for smaller address space
  coverage:
    addr_ranges:
    - name: low
      range:
      - 0
      - 15
    - name: mid
      range:
      - 16
      - 31
    - name: high
      range:
      - 32
      - 60
    corner_cases:
    - 'boundary_addr: 0x0'
    - 'boundary_addr: 0x3C'
